---
- hosts: dvr
  become: true

  handlers:
    - name: Restart zoneminder
      community.docker.docker_compose:
        project_src: "~/zoneminder/"
        build: false
        restarted: true
      become: false

  pre_tasks:
    - name: Update apt cache.
      ansible.builtin.apt: update_cache=yes cache_valid_time=600

  tasks:
    - name: Ensure pip is installed.
      ansible.builtin.apt:
        name: python3-pip
        state: present

    - name: Install required python libraries.
      ansible.builtin.pip:
        name:
          - docker
          - docker-compose
        state: present

    - name: Create ZoneMinder folder on Pi.
      ansible.builtin.file:
        path: "~/zoneminder"
        state: directory
        mode: '0755'
      become: false

    - name: Copy ZoneMinder docker-compose template to Pi.
      ansible.builtin.template:
        src: docker-compose.yml
        dest: "~/zoneminder/docker-compose.yml"
        mode: '0640'
      become: false
      notify: Restart zoneminder

    - name: Ensure ZoneMinder is running.
      community.docker.docker_compose:
        project_src: "~/zoneminder/"
        build: false
      become: false
