---
- hosts: dvr
  become: true

  vars:
    frigate_storage_path: /mnt/frigate

  handlers:
    - name: Restart frigate
      community.docker.docker_compose:
        project_src: "~/frigate/"
        build: false
        restarted: true
      become: false

  pre_tasks:
    - name: Update apt cache.
      ansible.builtin.apt: update_cache=yes cache_valid_time=600

  tasks:
    - name: Ensure pip is installed.
      ansible.builtin.apt:
        name: python3-pip
        state: present

    - name: Install required python libraries.
      ansible.builtin.pip:
        name:
          - docker
          - docker-compose
        state: present

    - name: Create Frigate folder on Pi.
      ansible.builtin.file:
        path: "~/frigate"
        state: directory
        mode: '0755'
      become: false

    - name: Copy Frigate files to Pi.
      ansible.builtin.template:
        src: "{{ item }}"
        dest: "~/frigate/{{ item }}"
        mode: '0640'
      become: false
      notify: Restart frigate
      with_items:
        - docker-compose.yml.j2
        - frigate.yml.j2

    - name: Ensure Frigate is running.
      community.docker.docker_compose:
        project_src: "~/frigate/"
        build: false
      become: false
