---
- hosts: dvr
  become: true

  vars:
    frigate_storage_path: /mnt/frigate

  handlers:
    - name: Restart frigate
      community.docker.docker_compose:
        project_src: "~/frigate/"
        build: false
        restarted: true
      become: false

  pre_tasks:
    - name: Update apt cache.
      ansible.builtin.apt: update_cache=yes cache_valid_time=600

  tasks:
    - name: Ensure pip is installed.
      ansible.builtin.apt:
        name: python3-pip
        state: present

    - name: Install required python libraries.
      ansible.builtin.pip:
        name:
          - docker
          - docker-compose
        state: present

    - name: Create Frigate folders on Pi.
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
        mode: '0755'
      become: false
      with_items:
        - "~/frigate"
        - "~/frigate/mosquitto"
        - "~/frigate/mosquitto/logs"
      register: create_folders

    - name: Copy Frigate files to Pi.
      ansible.builtin.template:
        src: "{{ item }}.j2"
        dest: "~/frigate/{{ item }}"
        mode: '0640'
      become: false
      notify: Restart frigate
      with_items:
        - docker-compose.yml
        - frigate.yml
        - mosquitto/mosquitto.conf
        - mosquitto/mqtt-auth.conf
        - mosquitto/mqtt-acl.conf

    - name: Ensure Frigate is running.
      community.docker.docker_compose:
        project_src: "~/frigate/"
        build: false
      become: false

    # TODO: This is the right command... but it doesn't seem to be running.
    - name: Encrypt the mosquitto passwords.
      community.docker.docker_container_exec:
        container: mqtt
        command: 'mosquitto_passwd -U /mosquitto/config/mqtt-auth.conf'
      when: frigate_configure_mqtt_broker
