version: "3"
services:
  shinobi:
    # See: https://github.com/geerlingguy/pi-nvr/issues/1
    # image: registry.gitlab.com/shinobi-systems/shinobi:dev
    build: .
    container_name: shinobi
    environment:
      - PLUGIN_KEYS=''
      - SSL_ENABLED='false'
    volumes:
      - $HOME/shinobi/config:/config
      - $HOME/shinobi/customAutoLoad:/home/Shinobi/libs/customAutoLoad
      - $HOME/shinobi/database:/var/lib/mysql
      - $HOME/shinobi/videos:/home/Shinobi/videos
      - $HOME/shinobi/plugins:/home/Shinobi/plugins
      - /dev/shm/shinobi/streams:/dev/shm/streams
    ports:
      - 8080:8080
    restart: unless-stopped
